# Generated by Django 5.1.1 on 2024-10-19 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0005_rename_image_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='status_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mini_fb.statusmessage'),
        ),
    ]
